// ============================================================
// Midwife App — Localization strings
// ============================================================

export const en = {
  "action.resume": "Resume",
  "action.start": "Start recording",
  "action.view": "View",
  "app.logout": "Log out",
  "app.profileAria": "Open my profile",
  "auth.backToLogin": "Back to log in",
  "banner.offline": "Offline — recordings are saved locally and synced later",
  "banner.offlineQueue": "(3 in queue)",
  "common.cancel": "Cancel",
  "common.login": "Log in",
  "common.logout": "Log out",
  "create.admTime": "Admission time",
  "create.first": "First name",
  "create.ks": "Room",
  "create.last": "Last name",
  "create.num": "Patient no.",
  "create.privacy": "Patient data is stored securely.",
  "create.submit": "Create case",
  "create.subtitle": "Enter the patient’s master data",
  "create.title": "Create new case",
  "error.emailInvalid": "Please enter a valid email address",
  "error.emailRequired": "Email address is required",
  "error.passwordLength": "Password must be at least 4 characters",
  "error.passwordRequired": "Password is required",
  "error.passwordsMustMatch": "Passwords must match",
  "error.pinLength": "PIN must be exactly 6 digits",
  "error.pinNumeric": "PIN must contain digits only",
  "error.pinRequired": "PIN is required",
  "error.pinsMustMatch": "PINs must match",
  "error.usernameLength": "Username must be at least 3 characters",
  "error.usernameRequired": "Username is required",
  "filter.active": "Active",
  "filter.closed": "Completed",
  "forgot.body": "Enter your email address and we\u2019ll send you a link to reset your password.",
  "forgot.email": "Email address",
  "forgot.help": "Demo mode: any email triggers a simulated reset link.",
  "forgot.submit": "Send reset link",
  "forgot.subtitle": "We\u2019ll send you a reset link",
  "forgot.success": "If an account with this email exists, a reset link has been sent. Please check your inbox.",
  "forgot.title": "Forgot password?",
  "login.email": "Email",
  "login.hide": "Hide",
  "login.password": "Password",
  "login.show": "Show",
  "login.subtitle": "Log in",
  "patient.adm": "Adm.",
  "patient.closedOn": "Completed",
  "patient.emptyBody": "No patient is currently assigned to you. Create a new case to start documenting.",
  "patient.emptyTitle": "No cases yet",
  "patient.myCases": "My cases",
  "patient.newCase": "New case",
  "patient.newTag": "Newly assigned",
  "patient.noClosed": "No completed cases.",
  "patient.noResultsPre": "No patient found for",
  "patient.search": "Search name or patient no.",
  "patient.title": "Select patient",
  "pin.confirm": "Confirm PIN",
  "pin.new": "New PIN (6 digits)",
  "pin.save": "Save PIN",
  "pin.success": "Your new PIN has been saved.",
  "pin.title": "Set new PIN",
  "pwd.confirm": "Confirm new password",
  "pwd.new": "New password",
  "pwd.rule8": "At least 8 characters",
  "pwd.ruleSpecial": "At least one special character (e.g. ! @ # $)",
  "pwd.ruleUpper": "At least one uppercase letter and one number",
  "setup.body": "Create your account credentials to access the app.",
  "setup.submit": "Create account",
  "setup.subtitle": "First-time setup",
  "setup.success": "Account created successfully! You can now log in.",
  "setup.title": "Complete first-time setup",
  "setup.username": "Username",
  "sort.admission": "Admission",
  "sort.az": "A–Z",
  "sort.label": "Sort",
  "sort.recent": "Recent",
  "status.done": "Completed",
  "status.open": "Open",
  "status.running": "In progress",
} as const;

export const de = {
  "action.resume": "Fortsetzen",
  "action.start": "Aufnahme starten",
  "action.view": "Ansehen",
  "app.logout": "Abmelden",
  "app.profileAria": "Mein Profil öffnen",
  "auth.backToLogin": "Zurück zur Anmeldung",
  "banner.offline": "Offline — Aufnahmen werden lokal gespeichert und später synchronisiert",
  "banner.offlineQueue": "(3 in Warteschlange)",
  "common.cancel": "Abbrechen",
  "common.login": "Anmelden",
  "common.logout": "Abmelden",
  "create.admTime": "Aufnahmezeit",
  "create.first": "Vorname",
  "create.ks": "Raum",
  "create.last": "Nachname",
  "create.num": "Pat.-Nr.",
  "create.privacy": "Patientendaten werden sicher gespeichert.",
  "create.submit": "Fall anlegen",
  "create.subtitle": "Stammdaten der Patientin erfassen",
  "create.title": "Neuen Fall anlegen",
  "error.emailInvalid": "Geben Sie eine gültige E-Mail-Adresse ein",
  "error.emailRequired": "E-Mail-Adresse ist erforderlich",
  "error.passwordLength": "Passwort muss mindestens 4 Zeichen lang sein",
  "error.passwordRequired": "Passwort ist erforderlich",
  "error.passwordsMustMatch": "Passwörter müssen übereinstimmen",
  "error.pinLength": "PIN muss genau 6 Stellen haben",
  "error.pinNumeric": "PIN darf nur Ziffern enthalten",
  "error.pinRequired": "PIN ist erforderlich",
  "error.pinsMustMatch": "PINs müssen übereinstimmen",
  "error.usernameLength": "Benutzername muss mindestens 3 Zeichen lang sein",
  "error.usernameRequired": "Benutzername ist erforderlich",
  "filter.active": "Aktiv",
  "filter.closed": "Abgeschlossen",
  "forgot.body": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
  "forgot.email": "E-Mail-Adresse",
  "forgot.help": "Demo-Modus: Jede E-Mail-Adresse löst einen simulierten Reset-Link aus.",
  "forgot.submit": "Reset-Link senden",
  "forgot.subtitle": "Wir senden Ihnen einen Reset-Link",
  "forgot.success": "Falls ein Konto mit dieser E-Mail-Adresse existiert, wurde ein Reset-Link gesendet. Bitte prüfen Sie Ihren Posteingang.",
  "forgot.title": "Passwort vergessen?",
  "login.email": "E-Mail",
  "login.hide": "Verbergen",
  "login.password": "Passwort",
  "login.show": "Anzeigen",
  "login.subtitle": "Anmelden",
  "patient.adm": "Aufnahme",
  "patient.closedOn": "Abgeschlossen",
  "patient.emptyBody": "Ihnen ist derzeit keine Patientin zugewiesen. Legen Sie einen neuen Fall an, um mit der Dokumentation zu beginnen.",
  "patient.emptyTitle": "Noch keine Fälle",
  "patient.myCases": "Meine Fälle",
  "patient.newCase": "Neuen Fall anlegen",
  "patient.newTag": "Neu zugewiesen",
  "patient.noClosed": "Keine abgeschlossenen Fälle.",
  "patient.noResultsPre": "Keine Patientin gefunden für",
  "patient.search": "Name oder Pat.-Nr. suchen",
  "patient.title": "Patientin wählen",
  "pin.confirm": "PIN bestätigen",
  "pin.new": "Neue PIN (6 Stellen)",
  "pin.save": "PIN speichern",
  "pin.success": "Ihre neue PIN ist gespeichert.",
  "pin.title": "Neue PIN festlegen",
  "pwd.confirm": "Neues Passwort bestätigen",
  "pwd.new": "Neues Passwort",
  "pwd.rule8": "Mindestens 8 Zeichen",
  "pwd.ruleSpecial": "Mindestens ein Sonderzeichen (z. B. ! @ # $)",
  "pwd.ruleUpper": "Mindestens ein Großbuchstabe und eine Zahl",
  "setup.body": "Erstellen Sie Ihre Konto-Zugangsdaten, um die App zu nutzen.",
  "setup.submit": "Konto erstellen",
  "setup.subtitle": "Erstanmeldung",
  "setup.success": "Konto erfolgreich erstellt! Sie können sich jetzt anmelden.",
  "setup.title": "Erstanmeldung abschließen",
  "setup.username": "Benutzername",
  "sort.admission": "Aufnahmezeit",
  "sort.az": "A–Z",
  "sort.label": "Sortieren",
  "sort.recent": "Zuletzt",
  "status.done": "Abgeschlossen",
  "status.open": "Offen",
  "status.running": "Aufnahme läuft",
} as const;

export const Translations = {
  en,
  de,
} as const;

export type TranslationKey = keyof typeof en;
